// Re-export all database types for convenient importing throughout the app
export type {
  Database,
  Json,
  UserRole,
  Profile,
  ProfileInsert,
  ProfileUpdate,
  Project,
  ProjectInsert,
  ProjectUpdate,
  SavedOutput,
  SavedOutputInsert,
  SavedOutputUpdate,
  ChatMessage,
  ChatMessageInsert,
  ChatMessageUpdate,
  Assistant,
  AssistantProvider,
  AdminEventLog,
  AdminTemplate,
  AdminTemplateStatus,
  AdminKnowledgeSource,
  KnowledgeStatus,
  AdminSetting,
  AdminLogSeverity,
} from "@/types/database";
